language: ruby
cache: bundler
rvm:
  - 2.1.3

before_script:
  - sudo add-apt-repository ppa:archivematica/externals -y
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

script: bundle exec rspec
