language: ruby
cache: bundler
rvm:
  - 2.2.1
  - 2.1.5
  - 1.9.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head

before_script:
  - sudo add-apt-repository ppa:archivematica/externals -y
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

script: bundle exec rspec
