language: ruby
cache: bundler
rvm:
  - 2.2.1
  - 2.1.5
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0.0

before_script:
  - sudo add-apt-repository ppa:archivematica/externals -y
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

script: bundle exec rspec
